[Fix] bin/openstack: pyenv-virtualenvが存在しない場合の処理を追加

diff --git a/bin/openstack b/bin/openstack
--- a/bin/openstack
+++ b/bin/openstack
@@ -16,6 +16,11 @@ if ! type pyenv > /dev/null 2>&1; then
     exit 1
 fi
 
+if ! pyenv virtualenvs > /dev/null 2>&1; then
+    echo 'pyenv virtualenv not found'
+    exit 1
+fi
+
 # ${PYENV_LOCAL_DIRECTORY} がDirectoryか確認
 if [[ ! -d ${PYENV_LOCAL_DIRECTORY} ]]; then
 
